version: '2'

services:
 master:
  image: registry.cn-hangzhou.aliyuncs.com/omega-reg/swarm:1.2.4
  restart: always
  network_mode: host
  pid: host
  labels:
   - com.github.omega.labels.system=true
  command: manage --host 0.0.0.0:2375 ${DISCOVERY_URL}
 agent:
  image: registry.cn-hangzhou.aliyuncs.com/omega-reg/swarm:1.2.4
  restart: always
  network_mode: host
  pid: host
  labels:
   - com.github.omega.labels.system=true
  command: join --addr ${DOCKER_IP}:2376  ${DISCOVERY_URL}
 api:
  image: registry.cn-hangzhou.aliyuncs.com/omega-reg/api:1.0.0
  restart: always
  network_mode: host
  pid: host
  labels:
   - com.github.omega.labels.system=true
  command: /opt/omega/api -l debug start --clusterEndpoint=localhost:2375 --clusterScheme=http
